version: '3.4'

services:

  catalog.api:
    image: ${DOCCKER_REGISTRY-}catalogapi
    build:
      context: ../
      dockerfile: ../src/Services/Catalog/infrastructure/Dockerfile
  catalog.db:
    image: mongo

  basket.api:
    image: ${DOCCKER_REGISTRY-}basketapi
    build:
      context: ../
      dockerfile: ../src/Services/Basket/infrastructure/Dockerfile
  basket.db:
    image: redis:alpine
    
  discount.db:
    image: postgres
  
  pgadmin:
    image: dpage/pgadmin4
  
  portainer:
    image: portainer/portainer-ce
      
volumes: 
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data: