version: '3.4'

services:
  catalog.db:
    image: mongo
    
  catalog.api:
    image: ${DOCCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/infrastructure/Dockerfile
      
volumes: 
  mongo_data: 